spring:    
  application:
    name: school-service   #current service name to be used by the eureka server
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    appname: _03_spring-boot-eureka-client-school # ==> This is a instance of student-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
server:
  port: 8082    #default port where the service will be started

#  devtools:
#    livereload:
#      port: 35730        
#  management:
#    security:
#      enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
#
#logging:
#  level:
#    com.omermetin: DEBUG
    

